#!/bin/sh
#
# Auto increment version number of the version file
#
# To enable this hook, copy it to .git/hooks/pre-commit

# Increment last number in version
# https://stackoverflow.com/questions/8653126/how-to-increment-version-number-in-a-shell-script
increment_version ()
{
  declare -a part=( ${1//\./ } )
  declare    new
  declare -i carry=1

  for (( CNTR=${#part[@]}-1; CNTR>=0; CNTR-=1 )); do
    len=${#part[CNTR]}
    new=$((part[CNTR]+carry))
    [ ${#new} -gt $len ] && carry=1 || carry=0
    [ $CNTR -gt 0 ] && part[CNTR]=${new: -len} || part[CNTR]=${new}
  done
  new="${part[*]}"
  echo -e "${new// /.}"
} 

git_root=`git rev-parse --show-toplevel`
version_file=$git_root/Documentation/Procedurier/version.tex

# increment version of the document
current_version=`cat $version_file`
new_version=`increment_version $current_version`
echo $new_version > $version_file

git add *version.tex
